import streamlit as st
from fpdf import FPDF
import datetime
from pathlib import Path
import pytz
import requests
import base64
import json
import unicodedata

# ---- CONFIGURATION ----
ADMIN_EMAIL = "alexandre.moiteiro@gmail.com"
WEBSITE_LINK = "https://mass-balance.streamlit.app/"
SENDGRID_API_KEY = st.secrets["SENDGRID_API_KEY"]

def ascii_safe(text):
    if not isinstance(text, str):
        return str(text)
    return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')

class CustomPDF(FPDF):
    def footer(self):
        self.set_y(-10)
        self.set_font("Arial", 'I', 6)
        self.set_text_color(140, 140, 140)
        footer_text = (
            "This document is for assistance and cross-checking only. "
            "It does not replace your responsibility to perform and verify your own calculations before flight.\n  "
            f"Generated by {WEBSITE_LINK}"
        )
        self.multi_cell(0, 2.8, ascii_safe(footer_text), align='C')
        self.set_text_color(0,0,0)

st.set_page_config(
    page_title="Mass & Balance Planner",
    page_icon="🛩️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Modern global CSS
def inject_css():
    st.markdown("""
    <style>
    html, body, [class*="css"] {
        font-family: 'Segoe UI', 'Inter', 'Roboto', Arial, sans-serif;
        background: #f6f8fa;
        color: #1a2233;
        font-size: 17px;
    }
    .block-container { max-width: 980px !important; margin: auto;}
    .main { background: #f6f8fa; }
    .app-header { font-size:2.7rem; font-weight:700; color:#195ba6; letter-spacing:2px; margin:0.4em 0 0.2em 0; text-align:center;}
    .section-card {
        background: #fff;
        border-radius: 15px;
        box-shadow: 0 4px 16px #0012;
        padding: 2.1em 2em 1.7em 2em;
        margin-bottom: 22px;
        transition: box-shadow .17s;
    }
    .section-title { font-size:1.35rem; font-weight:600; color:#16518a; margin-bottom:1em; letter-spacing:.3px;}
    .input-label {font-size:1.01rem;color:#375184;font-weight:600;margin-bottom:.3em;}
    .summary-row {display:flex;justify-content:space-between;align-items:center;margin:.14em 0;}
    .summary-val {font-weight:700;font-size:1.12em;}
    .summary-limit-ok {color:#218c43;}
    .summary-limit-warn {color:#ff9500;}
    .summary-limit-bad {color:#c1121f;}
    .alert-card {
        background: #fde8e8;
        border-left: 6px solid #c1121f;
        color: #b30000;
        font-weight:500;
        border-radius:7px;
        padding:.6em 1.1em;
        margin: .5em 0 1em 0;
        font-size:1.09rem;
    }
    .info-tag {
        background: #eaf1fa;
        color: #195ba6;
        font-weight:600;
        border-radius: 7px;
        padding: .4em 1.1em;
        display: inline-block;
        margin-bottom: .8em;
        font-size: 1rem;
    }
    .limits-list {margin:0 0 8px 0;padding:0;list-style-type:none;}
    .limits-list li {margin:0 0 4px 0;}
    .mb-table {
        border-collapse:collapse;
        width:100%;
        background: #fcfcfd;
        border-radius:12px;
        overflow:hidden;
        margin: 6px 0 20px 0;
        font-size:1.07rem;
        box-shadow:0 2px 8px #0001;
    }
    .mb-table th, .mb-table td {padding:.7em 0.9em;text-align:center;}
    .mb-table th {background:#f5f8fb;color:#195ba6;font-weight:600;}
    .mb-table tr:not(:last-child) td {border-bottom:1px solid #e5e8ee;}
    .footer {margin-top:44px;font-size:0.99rem;color:#999;text-align:center;}
    .contact-card {background:#f8fafd;padding:1.2em 1.3em 1em 1.3em;border-radius:13px;border:1.5px solid #e4e8f0;max-width:450px;margin:12px auto;}
    .required-label {color:#b30000;font-weight:bold;}
    </style>
    """, unsafe_allow_html=True)
inject_css()

# ---- Aircraft data ----
aircraft_data = {
    "Tecnam P2008": {
        "fuel_arm": 2.209,
        "pilot_arm": 1.800,
        "baggage_arm": 2.417,
        "max_takeoff_weight": 650,
        "max_fuel_volume": 124.0,
        "max_passenger_weight": 230,
        "max_baggage_weight": 20,
        "cg_limits": (1.841, 1.978),
        "fuel_density": 0.72,
        "units": {"weight": "kg", "arm": "m"}
    }
}
icons = {
    "Tecnam P2008": "tecnam_icon.png"
}
afm_files = {
    "Tecnam P2008": "Tecnam_P2008_AFM.pdf"
}

def get_limits_text(ac):
    units = ac["units"]["weight"]
    arm_unit = ac["units"]["arm"]
    lines = [
        f"Max Takeoff Weight: <b>{ac['max_takeoff_weight']} {units}</b>",
        f"Max Fuel Volume: <b>{ac['max_fuel_volume']} {'L' if units == 'kg' else 'gal'}</b>",
    ]
    if ac.get("max_passenger_weight"):
        lines.append(f"Max Pilot+Passenger: <b>{ac['max_passenger_weight']} {units}</b>")
    lines.append(f"Max Baggage: <b>{ac['max_baggage_weight']} {units}</b>")
    if ac.get("cg_limits"):
        lines.append(f"CG Limits: <b>{ac['cg_limits'][0]} to {ac['cg_limits'][1]} {arm_unit}</b>")
    return lines

def get_color(val, limit):
    if limit is None: return "summary-limit-ok"
    if val > limit:
        return "summary-limit-bad"
    elif val > (limit * 0.95):
        return "summary-limit-warn"
    else:
        return "summary-limit-ok"

def get_cg_color(cg, limits):
    if not limits: return "summary-limit-ok"
    mn, mx = limits
    margin = (mx - mn) * 0.05
    if cg < mn or cg > mx:
        return "summary-limit-bad"
    elif cg < mn + margin or cg > mx - margin:
        return "summary-limit-warn"
    else:
        return "summary-limit-ok"

def utc_now():
    return datetime.datetime.now(pytz.UTC)

# ---- Sidebar ----
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2857/2857447.png", width=80)
    st.markdown('<div class="app-header" style="font-size:2.1rem;text-align:left;padding-bottom:.2em;">Mass & Balance</div>', unsafe_allow_html=True)
    aircrafts = list(aircraft_data.keys()) + ["(Soon: more aircraft!)"]
    aircraft = st.selectbox("Aircraft type", aircrafts, index=0)
    if aircraft not in aircraft_data:
        st.info("Only Tecnam P2008 available now. More soon!")
        st.stop()
    ac = aircraft_data[aircraft]
    st.markdown("<div class='section-title'>Operational Limits</div>", unsafe_allow_html=True)
    st.markdown(
        "<ul class='limits-list'>" +
        "".join([f"<li>🟦 {l}</li>" for l in get_limits_text(ac)]) +
        "</ul>", unsafe_allow_html=True)
    afm_path = afm_files.get(aircraft)
    if afm_path and Path(afm_path).exists():
        with open(afm_path, "rb") as f:
            st.download_button("Download AFM", f, file_name=afm_path, mime="application/pdf")
    st.markdown("—", unsafe_allow_html=True)

# ---- HEADER ----
st.markdown(f"<div class='app-header'>{aircraft}</div>", unsafe_allow_html=True)
st.write("")

# ---- INPUT FORM ----
with st.form(key="mass_input"):
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">Input Masses</div>', unsafe_allow_html=True)
    cols = st.columns(3)
    with cols[0]:
        ew = st.number_input(
            "Empty Weight (kg)",
            min_value=0.0, value=0.0, step=1.0,
            help="You can find the empty weight on the aircraft's weight & balance sheet.",
            key="ew"
        )
        ew_moment = st.number_input(
            "Empty Weight Moment (kg·m)",
            min_value=0.0, value=0.0, step=1.0,
            help="You can find the empty weight moment on the aircraft's weight & balance sheet.",
            key="ew_moment"
        )
        ew_arm = ew_moment / ew if ew > 0 else 0.0
    with cols[1]:
        pilot = st.number_input(
            "Pilot & Passenger (kg)",
            min_value=0.0, value=0.0, step=1.0,
            help="Total occupants weight",
            key="pilot"
        )
        bag1 = st.number_input(
            "Baggage (kg)",
            min_value=0.0, value=0.0, step=1.0,
            key="bag1"
        )
        bag2 = 0.0
    with cols[2]:
        fuel_mode = st.radio(
            "Fuel Input Mode",
            ["Automatic maximum fuel (default)", "Manual fuel volume"],
            index=0,
            key="fuel_mode",
            help="Automatic: maximize fuel as per limits. Manual: specify volume."
        )
        if fuel_mode == "Manual fuel volume":
            fuel_vol = st.number_input("Fuel Volume (L)", min_value=0.0, value=0.0, step=1.0, key="fuel_vol")
            fuel_density = ac['fuel_density']
            fuel_weight = fuel_vol * fuel_density
    st.form_submit_button("Recalculate", use_container_width=True)
    st.markdown('</div>', unsafe_allow_html=True)

fuel_density = ac['fuel_density']
units_wt = ac['units']['weight']
units_arm = ac['units']['arm']

if fuel_mode == "Automatic maximum fuel (default)":
    useful_load = ac['max_takeoff_weight'] - (ew + pilot + bag1 + bag2)
    fuel_weight_possible = max(0.0, useful_load)
    tank_capacity_weight = ac['max_fuel_volume'] * fuel_density
    if fuel_weight_possible <= tank_capacity_weight:
        fuel_weight = fuel_weight_possible
        fuel_vol = fuel_weight / fuel_density
        fuel_limit_by = "Maximum Weight"
    else:
        fuel_weight = tank_capacity_weight
        fuel_vol = ac['max_fuel_volume']
        fuel_limit_by = "Tank Capacity"
else:
    fuel_limit_by = "Manual Entry"

m_empty = ew_moment
m_pilot = pilot * ac['pilot_arm']
m_bag1 = bag1 * ac['baggage_arm']
m_bag2 = 0.0
m_fuel = fuel_weight * ac['fuel_arm']

total_weight = ew + pilot + bag1 + bag2 + fuel_weight
total_moment = m_empty + m_pilot + m_bag1 + m_bag2 + m_fuel
cg = (total_moment / total_weight) if total_weight > 0 else 0
baggage_sum = bag1 + bag2
alert_list = []

if total_weight > ac['max_takeoff_weight']:
    alert_list.append("Total weight exceeds maximum takeoff weight!")
if bag1 > ac['max_baggage_weight']:
    alert_list.append("Baggage exceeds limit!")
if ac.get("max_passenger_weight") and pilot > ac["max_passenger_weight"]:
    alert_list.append("Pilot & Passenger exceed limit!")
if ac['cg_limits']:
    mn, mx = ac['cg_limits']
    if cg < mn or cg > mx:
        alert_list.append("CG outside safe envelope!")

def summary_row(label, value, color_class=""):
    return f"<div class='summary-row'><div>{label}</div><div class='summary-val {color_class}'>{value}</div></div>"

fuel_str = (
    f"Fuel possible: <span class='summary-val summary-limit-ok'>{fuel_vol:.1f} L / {fuel_weight:.1f} {units_wt}</span> "
    f"<span class='info-tag'>{'Limited by tank capacity' if fuel_limit_by == 'Tank Capacity' else 'Limited by maximum weight'}</span>"
    if fuel_mode == "Automatic maximum fuel (default)"
    else f"Fuel: <span class='summary-val summary-limit-ok'>{fuel_vol:.1f} L / {fuel_weight:.1f} {units_wt}</span>"
)

summary_lines = [
    fuel_str,
    summary_row(
        "Total Weight", f"{total_weight:.2f} {units_wt}",
        get_color(total_weight, ac['max_takeoff_weight'])
    ),
    summary_row("Total Moment", f"{total_moment:.2f} {units_wt}·{units_arm}"),
]
if ac['cg_limits']:
    summary_lines.append(summary_row(
        "CG", f"{cg:.3f} {units_arm}", get_cg_color(cg, ac['cg_limits'])
    ))
    summary_lines.append(
        f"<div style='font-size:0.99em;margin-top:2px;color:#888;'>CG Limits: {ac['cg_limits'][0]:.3f} to {ac['cg_limits'][1]:.3f} {units_arm}</div>"
    )

st.markdown('<div class="section-card">', unsafe_allow_html=True)
st.markdown('<div class="section-title">Summary</div>', unsafe_allow_html=True)
st.markdown("<br>".join(summary_lines), unsafe_allow_html=True)
if alert_list:
    for a in alert_list:
        st.markdown(f'<div class="alert-card">{a}</div>', unsafe_allow_html=True)
st.markdown('</div>', unsafe_allow_html=True)

# ---- Mass & Balance Table ----
def mb_table(items, units_wt, units_arm):
    table = '<table class="mb-table">'
    table += (
        "<tr>"
        "<th>Item</th>"
        f"<th>Weight ({units_wt})</th>"
        f"<th>Arm ({units_arm})</th>"
        f"<th>Moment ({units_wt}·{units_arm})</th>"
        "</tr>"
    )
    for i in items:
        table += f"<tr><td>{i[0]}</td><td>{i[1]:.2f}</td><td>{i[2]:.3f}</td><td>{i[3]:.2f}</td></tr>"
    table += "</table>"
    return table

st.markdown('<div class="section-card">', unsafe_allow_html=True)
st.markdown('<div class="section-title">Mass & Balance Table</div>', unsafe_allow_html=True)
items = [
    ("Empty Weight", ew, ew_arm, m_empty),
    ("Pilot & Passenger", pilot, ac['pilot_arm'], m_pilot),
    ("Baggage", bag1, ac['baggage_arm'], m_bag1),
    ("Fuel", fuel_weight, ac['fuel_arm'], m_fuel),
]
st.markdown(mb_table(items, units_wt, units_arm), unsafe_allow_html=True)
st.markdown('</div>', unsafe_allow_html=True)

# ---- PDF generation/email ----
def generate_pdf(aircraft, registration, mission_number, flight_datetime_utc, pilot_name,
                 ew, ew_arm, ew_moment, pilot, bag1, bag2, fuel_weight, fuel_vol,
                 m_empty, m_pilot, m_bag1, m_bag2, m_fuel,
                 total_weight, total_moment, cg, ac, fuel_limit_by, alert_list, baggage_sum):

    pdf = CustomPDF()
    pdf.set_auto_page_break(auto=True, margin=10)
    pdf.add_page()
    pdf.set_fill_color(25, 91, 166)
    pdf.rect(0, 0, 210, 17, 'F')
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(255,255,255)
    pdf.set_xy(10,6)
    pdf.cell(0, 8, ascii_safe("MASS & BALANCE REPORT"), ln=True, align='L')
    pdf.set_text_color(0,0,0)
    pdf.set_xy(10,19)
    pdf.ln(3)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 7, ascii_safe(f"{aircraft}  |  {registration}"), ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(0, 6, ascii_safe(f"Mission Number: {mission_number}"), ln=True)
    pdf.cell(0, 6, ascii_safe(f"Flight (UTC): {flight_datetime_utc}"), ln=True)
    pdf.cell(0, 6, ascii_safe(f"Prepared by: {pilot_name}"), ln=True)
    pdf.cell(0, 6, ascii_safe("Operator: Sevenair Academy"), ln=True)
    pdf.ln(2)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(0, 6, ascii_safe("Operational Limits:"), ln=True)
    pdf.set_font("Arial", '', 9)
    for line in get_limits_text(ac):
        pdf.cell(0, 5, ascii_safe(line.replace('<b>', '').replace('</b>', '')), ln=True)
    pdf.ln(1)
    pdf.set_font("Arial", 'B', 10)
    col_widths = [45, 36, 34, 55]
    headers = ["Item", f"Weight ({ac['units']['weight']})", f"Arm ({ac['units']['arm']})", f"Moment ({ac['units']['weight']}·{ac['units']['arm']})"]
    for h, w in zip(headers, col_widths):
        pdf.cell(w, 7, ascii_safe(h), border=1, align='C')
    pdf.ln()
    pdf.set_font("Arial", '', 9)
    rows = [
        ("Empty Weight", ew, ew_arm, ew_moment),
        ("Pilot & Passenger", pilot, ac['pilot_arm'], m_pilot),
        ("Baggage", bag1, ac['baggage_arm'], m_bag1),
        ("Fuel", fuel_weight, ac['fuel_arm'], m_fuel),
    ]
    for row in rows:
        for val, w in zip(row, col_widths):
            if isinstance(val, str):
                pdf.cell(w, 7, ascii_safe(val), border=1)
            else:
                pdf.cell(w, 7, ascii_safe(f"{val:.2f}" if isinstance(val, float) else str(val)), border=1, align='C')
        pdf.ln()
    pdf.ln(1)
    pdf.set_font("Arial", 'B', 10)
    pdf.set_text_color(25, 91, 166)
    fuel_str = f"Fuel: {fuel_vol:.1f} L / {fuel_weight:.1f} {ac['units']['weight']} ({'Limited by tank capacity' if fuel_limit_by == 'Tank Capacity' else 'Limited by maximum weight'})"
    pdf.cell(0, 6, ascii_safe(fuel_str), ln=True)
    pdf.set_text_color(0,0,0)
    pdf.cell(0, 6, ascii_safe(f"Total Weight: {total_weight:.2f} {ac['units']['weight']}"), ln=True)
    pdf.cell(0, 6, ascii_safe(f"Total Moment: {total_moment:.2f} {ac['units']['weight']}·{ac['units']['arm']}"), ln=True)
    if ac['cg_limits']:
        pdf.cell(0, 6, ascii_safe(f"CG: {cg:.3f} {ac['units']['arm']}"), ln=True)
    if alert_list:
        pdf.set_font("Arial", 'B', 9)
        pdf.set_text_color(200,0,0)
        for a in list(dict.fromkeys(alert_list)):
            pdf.cell(0, 6, ascii_safe(f"WARNING: {a}"), ln=True)
        pdf.set_text_color(0,0,0)
    return pdf

def email_pdf_to_admin(pdf_path, subject, pilot_name, registration, mission_number, flight_datetime_utc, aircraft):
    with open(pdf_path, "rb") as f:
        pdf_bytes = f.read()
    html_body = f"""
    <html>
    <body>
        <h2>Mass & Balance Report</h2>
        <table style='border-collapse:collapse;'>
            <tr><th align='left'>Pilot</th><td>{pilot_name}</td></tr>
            <tr><th align='left'>Aircraft</th><td>{aircraft} ({registration})</td></tr>
            <tr><th align='left'>Mission</th><td>{mission_number}</td></tr>
            <tr><th align='left'>Flight (UTC)</th><td>{flight_datetime_utc}</td></tr>
            <tr><th align='left'>Submitted from</th><td>{WEBSITE_LINK}</td></tr>
        </table>
        <p style='margin-top:1.5em;'>See attached PDF for details.</p>
    </body>
    </html>
    """
    data = {
        "personalizations": [
            {
                "to": [{"email": ADMIN_EMAIL}],
                "subject": subject
            }
        ],
        "from": {"email": "alexandre.moiteiro@gmail.com"},
        "content": [
            {
                "type": "text/html",
                "value": html_body
            }
        ]
    }
    data['attachments'] = [{
        "content": base64.b64encode(pdf_bytes).decode(),
        "type": "application/pdf",
        "filename": pdf_path,
        "disposition": "attachment"
    }]
    headers = {
        "Authorization": f"Bearer {SENDGRID_API_KEY}",
        "Content-Type": "application/json"
    }
    requests.post("https://api.sendgrid.com/v3/mail/send", data=json.dumps(data), headers=headers)

def send_suggestion_email(name, email, msg):
    html_body = f"""
    <html>
    <body>
        <h2>Suggestion, bug, or message via Mass & Balance</h2>
        <table style='border-collapse:collapse;'>
            <tr><th align='left'>Name</th><td>{name}</td></tr>
            <tr><th align='left'>Email</th><td>{email}</td></tr>
        </table>
        <p style='margin-top:1.2em;'><b>Message:</b><br>{msg}</p>
    </body>
    </html>
    """
    data = {
        "personalizations": [
            {
                "to": [{"email": ADMIN_EMAIL}],
                "subject": "Suggestion/Bug/Contact from Mass & Balance site"
            }
        ],
        "from": {"email": "alexandre.moiteiro@gmail.com"},
        "content": [
            {
                "type": "text/html",
                "value": html_body
            }
        ]
    }
    headers = {
        "Authorization": f"Bearer {SENDGRID_API_KEY}",
        "Content-Type": "application/json"
    }
    requests.post("https://api.sendgrid.com/v3/mail/send", data=json.dumps(data), headers=headers)

# ---- PDF Report Section ----
st.markdown('<div class="section-card">', unsafe_allow_html=True)
st.markdown('<div class="section-title">PDF Report</div>', unsafe_allow_html=True)
with st.expander("Generate PDF report", expanded=False):
    st.markdown('<span class="required-label">*</span> <span style="color:#b30000">Pilot name is required</span>', unsafe_allow_html=True)
    pilot_name = st.text_input('Pilot name / Prepared by *', value="")
    registration = st.text_input("Aircraft registration", value="CS-XXX")
    mission_number = st.text_input("Mission number", value="001")
    utc_today = utc_now()
    default_datetime = utc_today.strftime("%Y-%m-%d %H:%M UTC")
    flight_datetime_utc = st.text_input("Scheduled flight date and time (UTC)", value=default_datetime)
    pilot_name_valid = bool(pilot_name.strip())
    pdf_button = st.button("Generate PDF with current values", disabled=not pilot_name_valid)
    if pdf_button and pilot_name_valid:
        pdf = generate_pdf(
            aircraft, registration, mission_number, flight_datetime_utc, pilot_name,
            ew, ew_arm, ew_moment, pilot, bag1, bag2, fuel_weight, fuel_vol,
            m_empty, m_pilot, m_bag1, m_bag2, m_fuel, total_weight, total_moment, cg, ac, fuel_limit_by, alert_list, baggage_sum
        )
        pdf_file = f"mass_balance_mission{mission_number}.pdf"
        pdf.output(pdf_file)
        with open(pdf_file, "rb") as f:
            st.download_button("Download PDF", f, file_name=pdf_file, mime="application/pdf")
        st.success("PDF generated successfully!")
        try:
            email_pdf_to_admin(
                pdf_file,
                subject=f"Mass & Balance - {pilot_name.strip()}",
                pilot_name=pilot_name,
                registration=registration,
                mission_number=mission_number,
                flight_datetime_utc=flight_datetime_utc,
                aircraft=aircraft
            )
        except Exception as e:
            st.warning("Failed to send PDF to admin.")
st.markdown('</div>', unsafe_allow_html=True)

# ---- Contact / Footer ----
st.markdown('<div class="footer">Site developed by Alexandre Moiteiro. All rights reserved.</div>', unsafe_allow_html=True)
with st.expander("Contact administrator / Suggestion / Bug", expanded=False):
    st.markdown('<div class="contact-card">If you want to send a suggestion, report a bug or contact the site administrator, fill in below:</div>', unsafe_allow_html=True)
    sug_name = st.text_input("Your name", value="", key="sug_nome_footer")
    sug_email = st.text_input("Your email (optional)", value="", key="sug_email_footer")
    sug_msg = st.text_area("Message", height=70, max_chars=900, key="sug_msg_footer")
    sug_send = st.button("Send message", key="sug_btn_footer")
    if sug_send:
        if not sug_msg.strip():
            st.warning("Please write your message before sending.")
        else:
            send_suggestion_email(sug_name, sug_email, sug_msg)
            st.success("Message sent successfully! Thank you for your feedback.")

